### ISSUE TITLE
Add support for large messages via S3

### ISSUE THREAD

**Issue by adammead** [avioconsulting/mule-custom-logger#39]
Add support for use S3 buckets for large messages rather than splitting the message into multiple SQS messages.
See https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-s3-messages.html

**Comment by neckron** [comment]
@adammead could you comment and close this please?

**Comment by adesjardin** [comment]
This has been implemented in the latest changes to the SQS appender and won't be added directly to the logger itself.
