### ISSUE TITLE
Add support for automatic logging at the beginning and end of subflows

### ISSUE THREAD

**Issue by claytonflesher** [avioconsulting/mule-custom-logger#43]
Just as v2 has automatic logging for beginning and end of flows, add support for this in subflows as well.
Use the same flow logs checkbox there is now, just for subflows.

**Comment by manikmagar** [comment]
Flow execution logging is based on the notifications provided by the runtime. There are no similar notifications for Subflow which ultimately just executes in the same context as the calling flow. We could check flow-ref processor notifications and see if logging the start and end of that processor will help. Although, when calling async actions, the logs may not represent sub-flows execution.

**Comment by manikmagar** [comment]
@adesjardin @claytonflesher We implemented flow-ref span capture for the OTEL module by using a flow-ref and detecting if the target is a sub-flow or flow. We could use the same strategy to enable sub-flow start and end logs.

**Comment by manikmagar** [comment]
This can also be done with notifications for a flow-ref processor with sub-flow as a target. Log the start and end of the flow-ref processor with the target name.

**Comment by manikmagar** [comment]
Fixed with #74 and released with v3.0.0
