### ISSUE TITLE
DEBUG severity log messages are not showing up in the log

### ISSUE THREAD

**Issue by ghughlett** [avioconsulting/mule-custom-logger#47]
Using version 2.0.1 of logger from Maven Central.

- The avio-logger-config has a default Log Category of ${log.cat}
- The log4j2.xml has an asyncLogger defined of "<AsyncLogger name="${log.cat}" level="DEBUG"/>" 
- The flow start and end loggers are using DEBUG severity

When a request is run, only INFO messages for that log category appear in the output.

Attaching three files:
- log-output-debug.txt which has the flow log output with DEBUG severity defined.
- log-output-info.txt which shows the flow log output with INFO severity defined.
- log4j2.xml file (added .txt extension because GitHub doesn't support XML)

[log4j2-xml.txt](https://github.com/avioconsulting/mule-custom-logger/files/10922227/log4j2-xml.txt)
[log-output-debug.txt](https://github.com/avioconsulting/mule-custom-logger/files/10922229/log-output-debug.txt)
[log-output-info.txt](https://github.com/avioconsulting/mule-custom-logger/files/10922230/log-output-info.txt)

**Comment by tannersherman** [comment]
Closing this as was determined to be a configuration issue within the MuleSoft application. Used this MuleSoft help article to aid in resolution: https://help.mulesoft.com/s/article/How-to-use-properties-in-log4j2-Configuration-File
