### ISSUE TITLE
Duplicate Flow Logs

### ISSUE THREAD

**Issue by adesjardin** [avioconsulting/mule-custom-logger#49]
The notification listeners are being registered multiple times in some scenarios and then creating duplicate flow start/end logs.

**Comment by tannersherman** [comment]
@adesjardin Just asking but do we have any more information on how we can duplicate this error?

**Comment by adesjardin** [comment]
I don't think we know the specific way to reproduce it, but I think I can show you a few examples in running apps where we are seeing it and we can take a look at the code and see if we can quickly identify a possible root cause

**Comment by tannersherman** [comment]
@adesjardin Okay that would be great. Can you point me to those and/or provide the raw logs to include in this?
