### ISSUE TITLE
Using dataweave to set Message Attribute Mule 4.6.0

### ISSUE THREAD

**Issue by csumeet-avio** [avioconsulting/mule-custom-logger#70]
We are getting error with Mule Runtime 4.6.0 where logger uses dataweave to set the message attribute.

Error message is java.lang.IllegalAccessException: Class org.mule.weave.v2.module.pojo.reader.PropertyDefinition can not access a member of class com.avioconsulting.mule.logger.api.processor.KeyValuePair with modifiers “private”.

Here is the example of logger

<avio-logger:log config-ref=“AVIO_Logger_Config”
				doc:name=“Logger” doc:id=“0c7731cf-e3fa-4f6c-bf7f-a3f693168c5f”
				message=“Testing logger with message attribute”
				payload=‘#[write(payload, “application/json”)]’
				messageAttributes=’#[[{key: “env”, value:"test"}]]’/>

**Comment by manikmagar** [comment]
4.6.0 support is being added with Mule Logger 3.0. Currently, it is WIP - https://github.com/avioconsulting/mule-custom-logger/pull/69
